version: "3.8"

services:
  api01: &api
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    hostname: api01
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/rinha
      - SPRING_R2DBC_USERNAME=admin
      - SPRING_R2DBC_PASSWORD=123
      - SPRING_MAIN_BANNER-MODE=off
      - LOGGING_LEVEL_ROOT=OFF
      - SPRING_THREADS_VIRTUAL_ENABLED=false
      # - JAVA_TOOL_OPTIONS=-XX:+UseG1GC -Xms64m -Xmx128m -XX:MaxGCPauseMillis=100 -XX:G1HeapRegionSize=1M
      - JAVA_TOOL_OPTIONS=-XX:+UseParallelGC -Xms64m -Xmx128m
      # - JAVA_TOOL_OPTIONS=-XX:+UseZGC -Xms64m -Xmx128m

      # - SPRING_MAIN_LAZY_INITIALIZATION=true
      - SPRING.R2DBC_POOL_MAX-SIZE=10
      - SPRING.R2DBC_POOL_MIN-IDLE=5

    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "230MB"
  api02:
    <<: *api
    hostname: api02
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "230MB"
    ports:
      - "8082:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "25MB"
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
    ports:
      - "5432:5432"
    volumes:
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "65MB"
networks:
  default:
    driver: bridge
